(module
 (type $FUNCSIG$v (func))
 (memory $0 0)
 (table $0 1 funcref)
 (elem (i32.const 0) $null)
 (global $../../lib/constant/SHA256_LEN i32 (i32.const 32))
 (global $../../lib/constant/SHA512_LEN i32 (i32.const 64))
 (global $../../lib/constant/RIPEMD160_LEN i32 (i32.const 20))
 (global $../../lib/constant/ADDRESS_LEN i32 (i32.const 20))
 (global $../../lib/constant/SIGNATURE_LEN i32 (i32.const 96))
 (global $../../lib/constant/PUBLIC_KEY_LEN i32 (i32.const 32))
 (global $../../src/asset/UNIT i32 (i32.const 0))
 (global $../../src/asset/KUNIT i32 (i32.const 1))
 (global $../../src/asset/MUNIT i32 (i32.const 2))
 (global $../../src/asset/DOM i32 (i32.const 3))
 (export "memory" (memory $0))
 (export "apply" (func $serialize/apply))
 (func $serialize/apply (; 0 ;) (type $FUNCSIG$v)
  nop
 )
 (func $null (; 1 ;) (type $FUNCSIG$v)
 )
)
